services:
  glpi-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glpi-php
    volumes:
      - glpi_data:/var/www/glpi
    networks:
      - glpi-net

  glpi-nginx:
    image: nginx:1.24
    container_name: glpi-nginx
    ports:
      - "80:80"
    volumes:
      - glpi_data:/var/www/glpi
      - ./nginx/glpi.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - glpi-php
    networks:
      - glpi-net

  mysql:
    image: mysql:8.0
    container_name: glpi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpipass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - glpi-net

  redis:
    image: redis:7
    container_name: glpi-redis
    networks:
      - glpi-net

volumes:
  glpi_data:
  mysql_data:

networks:
  glpi-net: